### ISSUE TITLE
add `transfer` extrinsic

### ISSUE THREAD

**Issue by crazydevlegend** [crazydevlegend/multi-sig-app#8]
* **I'm submitting a ...**
  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

`transfer` is one of the main extrinsics, please add it to extrinsics list too

* **Please tell us about your environment:**
  - [ ] Node.js
  - [x] Browser
  - [ ] Other (limited support for other environments)

**Comment by ethsdev** [comment]
For all other multisig apps, and polkadot js app, it all have separated transfer function with extrinsic. And because account page, and multisig page have its own transfer(send) function, I think adding it to extrinsic is not needed. And I think adding it cause potential runtime bug because structure is too complex.

**Comment by crazydevlegend** [comment]
> For all other multisig apps, and polkadot js app, it all have separated transfer function with extrinsic. And because account page, and multisig page have its own transfer(send) function, I think adding it to extrinsic is not needed. And I think adding it cause potential runtime bug because structure is too complex.

`transfer` is another type of extrinsic which is exactly the same as other extrinsics (e.g. stake)

**Comment by crazydevlegend** [comment]
@solthereum

**Comment by ethsdev** [comment]
done!
